### ISSUE TITLE
Specify a file to store variables

### ISSUE THREAD

**Issue by shelegdmitriy** [near/near-discovery-components#127]
As a developer who want to build a responsive components I want to know exactly when `desktop` ends and `mobile` starts.

This is just a proposal inspired by `replacements ` functionality.

We can create a file `variables.json`(name could be different) and store all variables we want to be used across all the project. Then we add there a variable called `mobile` so this is how it looks like:
```
// variables.json
{
  "mobile": "900px"
}
```
of this:
```
// variables.json
{
  "MOBILE": "900px"
}
```

And now we could use this variable in the code like so:
```
const Main = styled.div`
  // rest of the code
  @media (max-width: ${mobile}) {
    display: block;
  }
`;
```

And now we need to add a github workflow to replace our variable with value like @milenakrawczyk did here https://github.com/near/near-discovery-components/blob/develop/.github/workflows/deploy-dev-testnet.yml#L18-L29

```
  // example from provided link

- name: Set replacements
        id: set_replacements
        run: |
          echo "replacements=$(jq -r '[to_entries[] | .["find"] = "${" + .key + "}" | .["replace"] = .value | del(.key, .value)]' replacements.dev.json | tr -d "\n\r")" >> $GITHUB_OUTPUT

      - name: Replace placeholders
        uses: flcdrg/replace-multiple-action@v1
        with:
          files: '**/*.jsx'
          find: '${{ steps.set_replacements.outputs.replacements }}'
          prefix: '(^|.*)'
          suffix: '($|.*)'
```
